### ISSUE TITLE
Drop header and footer into layout

### ISSUE THREAD

**Issue by jfols** [modweb/grant-application#17]
From CFi

**Comment by code-baker** [comment]
@jfols It appears some of the styling in the files I sent is being overridden or somehow have been adjusted. Do you know why this is? When I compare them side-by-side there are minor differences in the details of the design. I noticed issues with some of the <a> styling on buttons and links. As well some of the breakpoints are not reacting the same as they were before.

**Comment by jfols** [comment]
@andycfi the CSS provided doesn't seem to match what's on cultureworks.org. See this file http://cultureworks.org/wp-content/themes/churchhope-child/style.css and the classes applied to the navigation on cultureworks.org.

**Comment by jfols** [comment]
Continue discussion on new issue #18
