### ISSUE TITLE
Header and Footer CSS adjustments

### ISSUE THREAD

**Issue by jfols** [modweb/grant-application#18]
@andycfi It looks like you don't have any :hover :focus or :active states defined in your CSS, which are going to fall back onto bootstrap defaults. You mentioned there are other issues, please address them on this github issue.

**Comment by jfols** [comment]
@andycfi the footer is out of whack bc bootstrap 3 sets `box-sizing: border-box;` on everything, but your CSS layout doesn't expect `border-box`, you can fix this with

``` css
footer * {
  box-sizing: unset;
}
```

**Comment by jfols** [comment]
For more info on bootstrap and border-box see http://blog.getbootstrap.com/2013/08/19/bootstrap-3-released/

**Comment by code-baker** [comment]
thanks for all your suggestions and help on this one @jfols! I'll take a peek here soon!

**Comment by code-baker** [comment]
@jfols for whatever reason when I loaded up meteor it also wanted to change some versions. Not sure why, but I opted to not commit those changes. Do you know why it would do this?

https://www.dropbox.com/s/0fmoheek1qfe0l5/Screenshot%202015-02-19%2009.59.05.png?dl=0
