### ISSUE TITLE
Body wrapper sizing

### ISSUE THREAD

**Issue by jfols** [modweb/grant-application#27]
Set a max-width of 58.75ems (aka 940px) for the main body wrapper and position center equally (is this something Andy can adjust to the native styles.css file? If so tag Andy to it).

**Comment by code-baker** [comment]
I ended up simply using pixels and went with 930px since it looked better

**Comment by code-baker** [comment]
Just realized this effects all pages...need to revaluate the centering approach

**Comment by jfols** [comment]
This might have something to do with the flow, since I think you're not expecting border-box box-sizing in your layout but bootstrap is. This is a total guess though.
