### ISSUE TITLE
Styled header and footer

### ISSUE THREAD

**Issue by jfols** [modweb/grant-application#8]

**Comment by code-baker** [comment]
@jfols  Let me know when the drop-dead date is for this and we'll work from that. Thanks!

**Comment by jfols** [comment]
@andycfi Let's shoot for end of the week. Due date is Feb. 16th to avoid extending the deadline.

**Comment by jfols** [comment]
@andycfi, to clarify this task, I need the HTML and CSS you'd like to style the header and the footer of the app with. I will hook up the app navigation links, no need to modify links on your end.

**Comment by code-baker** [comment]
got it, thanks! This week may be tough, but we'll plan to work it in before the 16th.
